### ISSUE TITLE
Lab4

### ISSUE THREAD

**Issue by E1izabeth** [Elementarno9/ProgrammingLabs#3]
https://github.com/Elementarno9/ProgrammingLabs/blob/65b05288b6cec667ecb308625c636e2a4fe7dd90/Lab4/Program.cs#L47
Такой сплит (по пробелам) недостаточен для поведения в соответствии с заданием.

**Comment by Elementarno9** [comment]
#4 Исправлено

**Comment by E1izabeth** [comment]
>        static int CountWords(string line, int maxLength = 4)
>        {
>            int count = 0;
>            bad_symbols.ToList().ForEach((ch) => { line = line.Replace(ch, ' '); });
>            foreach (var word in line.Split().Where((s) => !string.IsNullOrWhiteSpace(s)))
>            {
>                if (!string.IsNullOrWhiteSpace(word) && word.Length <= maxLength) count++;
>            }
>            return count;
>        }   

Как можно записать этот код более компактно ввиду (уже) использования linq?
Каковы проблемы с эффективностью данного кода при обработке больших текстов?
Как можно решить эти проблемы?

**Comment by Elementarno9** [comment]
Возможно, неудобно хранить и обрабатывать весь текст в памяти, особенно если он достаточно большой. В качестве решения этой проблемы можно попробовать читать файл построчно (потому что слово так или иначе должно полностью находится на одной строке).

**Comment by E1izabeth** [comment]
Если не рассматривать вариант текста с переносами слов, то читать по одной строке можно, но это не решает проблему. Нам все равно так или иначе придётся считать весь текст. Проблема алгоритма в том, что по ходу обработки текста создается большой memory-трафик. Сколько раз весь текст будет скопирован в памяти в процессе выполнения данного алгоритма?

**Comment by Elementarno9** [comment]
Более 20 раз, а причина в том, что каждый раз создается новая строчка во время замены символов на пробелы. Тогда стоит обрабатывать не весь текст, а заменять символы в самих словах, потом отрезать лишние пробелы и считать слова. Тогда мы по всему тексту пройдемся лишь один раз, и memory-трафик должен уменьшиться в разы.

**Comment by Elementarno9** [comment]
Провел небольшое исследование и нашел решение этой проблемы.

Я тестировал программу на файле из 16 тыс. строк (около 4,8 Мб), содержащей точки и переносы строк (этого достаточно, так как программа так или иначе должно проверить на наличие всех неподходящих символов). Исходная программа тратила около **108 Мб** памяти (что в 22,5 раза больше исходного файла).

Попробовав поменять порядок обработки текста (удаление лишних символов не из всего текста, а из каждого слова), я не уменьшил потребление памяти, что, на самом деле, очевидно: столько же раз копировал текст, только теперь каждое слово в отдельности. (в каком-то смысле, это даже хуже исходного варианта). У меня появилась идея попробовать регулярные выражения: я знал, что они медленные, но я рассчитывал, что они не будут копировать столько раз текст. К сожалению, я получил только **86 Мб** memory-трафика (в 17,9 раза больше исходного файла).

На этом моменте ко мне пришла еще одна идея: зачем нам столько раз обрабатывать строки, если мы можем один раз пробежать по всему тексту и напрямую посчитать количество символов? Возможно, это будет не так хорошо выглядеть с точки зрения кода (мне пока не удалось в терминах LINQ записать), но с точки зрения скорости и потребления памяти у нас сложность O(n)! Результат уже впечатляет: память задействовала всего **29 Мб** (в 6 раз больше исходного файла). Я думаю, это не предел, но пока это максимум, который мне удалось получить. Что думаете?


**Память:** _(подскажите, если знаете, как лучше/удобнее это можно смотреть, чем во время отладки)_
![Обработка текста](https://user-images.githubusercontent.com/35084158/80192717-4ac94000-8620-11ea-9cf1-b0dca05c77e8.png)

**Код с Regex:**
```
static int CountWords(string line, int maxLength = 4)
{
    int count = 0;
    string pattern = @"\W+";
    line.Split().ToList().ForEach((word) =>
    {
        word = Regex.Replace(word, pattern, "");
        if (!string.IsNullOrWhiteSpace(word) && word.Length <= maxLength) count++;
    });
    return count;
}
```

**Последнее решение:**
```
static int CountWords(string line, int maxLength = 4)
{
    int count = 0;
    int buffer = 0;

    for (int i = 0; i < line.Length; i++)
    {
        if (line[i] != ' ' && !bad_symbols.Contains(line[i])) buffer++;
        else
        {
            if (buffer > 0 && buffer <= maxLength) count++;
            buffer = 0;
        }
    }

    return count;
}
```

**Comment by E1izabeth** [comment]
Отлично!

Оценка потребления памяти: или профилировщик (студийный или внешние), или можно посчитать экземпляры того, что ты создаешь по ходу программы (можно сделать ведение статистики в своей программе).

Как решить эту задачу красиво: проблема с Linq в том, что исходная модель данных неподходящая, Linq предназначен для работой с коллекциями, следовательно, сначала надо построить коллекцию, чтобы применять Linq.

Адекватный подход: разбить задачу на части. Нам нужна информация о структуре текста, о том, где и какой длины слова у нас есть. Чтобы выделить слова сплитить сам текст не нужно. Можно выделить одну доп коллекцию, на которую потом наложить условия, чтобы ответить на задания.

Можно решить это, например, так:

```
static void Main(string[] args)
{
    var text = File.ReadAllText(args[0]);
    Console.WriteLine(GetWordLengths(text).Count(l => l < 5));
}

static readonly char[] _wordSeparators = new[] { ' ', '\t', '!', '?' };

static IEnumerable<int> GetWordLengths(string text)
{
    var pos = 0;
    while (pos < text.Length)
    {
        SkipSeparators(text, ref pos);

        var length = CaptureWord(text, ref pos);
        if (length > 0)
            yield return length;
    }
}

static int CaptureWord(string text, ref int pos)
{
    var startPos = pos;
    while (pos < text.Length && !IsSeparator(text[pos]))
        pos++;

    return pos - startPos;
}

static void SkipSeparators(string text, ref int pos)
{
    while (pos < text.Length && IsSeparator(text[pos]))
        pos++;

}

static bool IsSeparator(char ch)
{
    return _wordSeparators.Contains(ch);
}
```
